import { ArrowUpRight, MapPin } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import { Button } from '@/components/ui/button';

export async function OpenPositions() {
  const supabase = createClient();
  const { data: links } = await supabase
    .from('application_links')
    .select('*')
    .eq('is_active', true)
    .order('created_at', { ascending: false })
    .limit(6);

  const positions = links ?? [];

  return (
    <section id="positions" className="bg-mist py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <span className="verified-chip">Open Positions</span>
          <h2 className="mt-4 font-display text-3xl font-bold text-ink-900 sm:text-4xl">Currently hiring</h2>
          <p className="mt-3 text-ink-600">Each posting below has its own application link generated by our HR team.</p>
        </div>

        <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {positions.length === 0 &&
            ['Frontend Developer Intern', 'UI/UX Design Intern', 'Backend Developer Intern'].map((title) => (
              <div key={title} className="rounded-2xl border border-ink-50 bg-white p-6 shadow-card">
                <p className="font-display font-semibold text-ink-900">{title}</p>
                <p className="mt-1 flex items-center gap-1 text-xs text-ink-400">
                  <MapPin size={12} /> Remote / Hybrid
                </p>
                <p className="mt-4 text-sm text-ink-400">Applications open soon — check back or contact HR for an invite link.</p>
              </div>
            ))}

          {positions.map((p: any) => (
            <div key={p.id} className="group rounded-2xl border border-ink-50 bg-white p-6 shadow-card transition-shadow hover:shadow-glass">
              <div className="flex items-start justify-between">
                <div>
                  <p className="font-display font-semibold text-ink-900">{p.role_title}</p>
                  <p className="mt-1 flex items-center gap-1 text-xs text-ink-400">
                    <MapPin size={12} /> {p.department ?? 'StoreShift'}
                  </p>
                </div>
                <span className="rounded-full bg-brand-50 px-2.5 py-1 text-[10px] font-semibold text-brand-700">Open</span>
              </div>
              <a href={`/apply/${p.code}`} className="mt-5 inline-block w-full">
                <Button size="sm" className="w-full group-hover:gap-2.5">
                  Apply Now <ArrowUpRight size={15} />
                </Button>
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
