import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient, createClient } from '@/lib/supabase/server';
import { sendEmail, renderStoredTemplate } from '@/lib/email/service';
import { brandedEmailShell, eyebrow, heading, emailButton } from '@/lib/email/templates';

const LABELS: Record<string, string> = {
  offer_letter: 'Offer Letter',
  certificate: 'Certificate of Internship',
  lor: 'Letter of Recommendation',
};

const TABLES: Record<string, string> = {
  offer_letter: 'offer_letters',
  certificate: 'certificates',
  lor: 'letters_of_recommendation',
};

/**
 * Admin-only: sends the intern a branded "your document is ready" email
 * after a certificate/offer-letter/LOR is generated or regenerated.
 * Wording comes from the 'document_ready' row in email_templates
 * (Settings → Email Templates), not hardcoded copy.
 *
 * Body: { kind: 'offer_letter' | 'certificate' | 'lor', internshipId, documentId }
 */
export async function POST(req: NextRequest) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { data: actorProfile } = await supabase.from('profiles').select('role, full_name').eq('id', user.id).single();
  if (!actorProfile) return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

  const { kind, internshipId, documentId } = await req.json();
  if (!kind || !TABLES[kind] || !internshipId || !documentId) {
    return NextResponse.json({ error: 'kind, internshipId, and documentId are required' }, { status: 400 });
  }

  const admin = createAdminClient();

  const { data: internship } = await admin
    .from('internships')
    .select('*, profiles!internships_intern_id_fkey(full_name, email)')
    .eq('id', internshipId)
    .single();

  if (!internship?.profiles) return NextResponse.json({ error: 'Intern not found' }, { status: 404 });

  const label = LABELS[kind];
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://careers.storeshift.in';

  let downloadUrl = `${siteUrl}/login`;
  let isDirectDownload = false;

  if (kind === 'certificate') {
    const { data: cert } = await admin.from('certificates').select('pdf_path').eq('id', documentId).maybeSingle();
    if (cert?.pdf_path) {
      const { data } = admin.storage.from('certificates').getPublicUrl(cert.pdf_path);
      downloadUrl = data.publicUrl;
      isDirectDownload = true;
    }
  }
  // Offer letters and LORs live in private buckets — a signed URL would
  // expire before the email is likely to be opened, so we point to the
  // dashboard instead, where a fresh signed URL is generated on demand.

  const { subject, bodyHtml } = await renderStoredTemplate(
    admin,
    'document_ready',
    { document_label: label, full_name: internship.profiles.full_name },
    { subject: 'Your {{document_label}} is ready — StoreShift', bodyHtml: '<p>Your <strong>{{document_label}}</strong> has been generated by the StoreShift team.</p>' }
  );

  const cta = emailButton(isDirectDownload ? `Download ${label}` : 'Go to Documents', downloadUrl);
  const html = brandedEmailShell(`${eyebrow('Document Ready')}${heading(`Your ${label} is ready`)}${bodyHtml}${cta}`);

  const result = await sendEmail({ to: internship.profiles.email, subject, html });

  await admin.from('email_log').insert({
    to_email: internship.profiles.email, subject, status: result.status,
    sent_by: user.id, provider_response: { kind: 'document_ready', documentKind: kind, providerId: result.id, error: (result as any).error ?? null },
  });

  return NextResponse.json({ status: result.status });
}
