import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient, createClient } from '@/lib/supabase/server';
import { sendEmail, renderStoredTemplate } from '@/lib/email/service';
import { brandedEmailShell, eyebrow, heading, emailButton, infoCard, footerNote } from '@/lib/email/templates';

const LABELS: Record<string, string> = {
  offer_letter: 'Offer Letter',
  certificate: 'Certificate of Internship',
  lor: 'Letter of Recommendation',
};

const TABLES: Record<string, string> = {
  offer_letter: 'offer_letters',
  certificate: 'certificates',
  lor: 'letters_of_recommendation',
};

const REF_COLUMNS: Record<string, string> = {
  offer_letter: 'offer_id',
  certificate: 'certificate_id',
  lor: 'lor_id',
};

const STAFF_ROLES = ['founder', 'super_admin', 'hr_manager', 'recruiter', 'mentor', 'technical_interviewer', 'certificate_manager'];

/**
 * SERVER-ONLY route. Sends the intern a branded "your document is ready"
 * email after a certificate/offer-letter/LOR is generated or
 * regenerated. This is the *only* place Client Components are allowed to
 * trigger a document-ready notification from — everything downstream of
 * here (sendEmail, Nodemailer, SMTP credentials) never runs in, or is
 * ever bundled for, the browser.
 *
 * Wording comes from the 'document_ready' row in email_templates
 * (Settings → Email Templates), not hardcoded copy.
 *
 * Body: { type: 'offer_letter' | 'certificate' | 'lor', internshipId, documentId }
 */
export async function POST(req: NextRequest) {
  const supabase = createClient();

  // getUser() — not getSession() — because this is an authorization
  // decision (does this caller get to trigger an email send), not just a
  // fast pre-check. getUser() re-validates the token against the Supabase
  // Auth server instead of trusting whatever the cookie claims.
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { data: actorProfile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  if (!actorProfile || !STAFF_ROLES.includes(actorProfile.role)) {
    return NextResponse.json({ error: 'Forbidden — staff access required' }, { status: 403 });
  }

  let body: any;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { type, internshipId, documentId } = body ?? {};
  if (!type || !TABLES[type] || !internshipId || !documentId) {
    return NextResponse.json(
      { error: 'type (offer_letter | certificate | lor), internshipId, and documentId are all required' },
      { status: 400 }
    );
  }

  try {
    const admin = createAdminClient();

    const { data: internship } = await admin
      .from('internships')
      .select('*, profiles!internships_intern_id_fkey(full_name, email)')
      .eq('id', internshipId)
      .single();

    if (!internship?.profiles) {
      return NextResponse.json({ error: 'Intern not found for that internship' }, { status: 404 });
    }

    const label = LABELS[type];
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://careers.storeshift.in';

    let downloadUrl = `${siteUrl}/login`;
    let isDirectDownload = false;

    const { data: docRow } = await admin.from(TABLES[type]).select('*').eq('id', documentId).maybeSingle();
    const refId = docRow?.[REF_COLUMNS[type]] ?? null;

    if (type === 'certificate' && docRow?.pdf_path) {
      const { data } = admin.storage.from('certificates').getPublicUrl(docRow.pdf_path);
      downloadUrl = data.publicUrl;
      isDirectDownload = true;
    }
    // Offer letters and LORs live in private buckets — a signed URL would
    // expire before the email is likely to be opened, so we point to the
    // dashboard instead, where a fresh signed URL is generated on demand.

    const { subject, bodyHtml } = await renderStoredTemplate(
      admin,
      'document_ready',
      { document_label: label, full_name: internship.profiles.full_name },
      {
        subject: 'Your {{document_label}} is ready — StoreShift',
        bodyHtml: '<p>Your <strong>{{document_label}}</strong> has been generated by the StoreShift team.</p>',
      }
    );

    const detailRows: [string, string][] = [
      ['Document', label],
      ['Role', internship.role_title],
      ['Department', internship.department],
    ];
    if (refId) detailRows.push(['Reference ID', refId]);
    const details = infoCard('Document Details', detailRows);

    const cta = emailButton(isDirectDownload ? `Download ${label}` : 'Go to Documents', downloadUrl);
    const closing = footerNote(
      isDirectDownload
        ? 'This link is permanent — feel free to share it (e.g. with a recruiter) or save it for your records.'
        : "For security, offer letters and recommendation letters are downloaded from your dashboard rather than linked directly in email. Log in any time to get the latest copy."
    );
    const html = brandedEmailShell(`${eyebrow('Document Ready')}${heading(`Your ${label} is ready`)}${bodyHtml}${details}${cta}${closing}`);

    const result = await sendEmail({ to: internship.profiles.email, subject, html });

    await admin.from('email_log').insert({
      to_email: internship.profiles.email,
      subject,
      status: result.status,
      sent_by: user.id,
      provider_response: { kind: 'document_ready', documentKind: type, providerId: result.id, error: (result as any).error ?? null },
    });

    return NextResponse.json({ status: result.status });
  } catch (err: any) {
    // Never leak provider/SMTP internals to the client — log server-side
    // detail is already captured in email_log where relevant.
    return NextResponse.json({ error: 'Failed to send document notification' }, { status: 500 });
  }
}
